### ISSUE TITLE
Me again feed read First itens only

### ISSUE THREAD

**Issue by krebinha** [ArjixWasTaken/random-rss-stuff-i-guess#1]
Hey, Very thanks for you job i love, but look this
https://rssviewer.app/https://github.com/ArjixWasTaken/random-rss-stuff-i-guess/raw/main/geralinks-feed.xml

Only show First item, in loop.

**Comment by ArjixWasTaken** [comment]
Not my problem that the site you are using is shitty.
My rss is valid and follows the spec.

Check out this site for example:
<a href="https://rssatom.com"><img src="https://user-images.githubusercontent.com/53124886/175079730-4bede25d-1347-4c47-a63e-3145220dabbe.png"></a>

**Comment by ArjixWasTaken** [comment]
any as I mentioned before, my rss is valid

<a href="https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fraw.githubusercontent.com%2FArjixWasTaken%2Frandom-rss-stuff-i-guess%2Fmain%2Fgeralinks-feed.xml"><img src="https://user-images.githubusercontent.com/53124886/175081269-8f319948-4fbd-432e-a3b7-5478e492049f.png"></a>

**Comment by justfoolingaround** [comment]
_L M F A O_
